import html
import json
from pathlib import Path
from .store import dump
from .predict import build_predictions
from .review import build_reviews

TEMPLATE = '''<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>ボートレース データ基盤</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e6edf7;font:15px system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:26px 18px}h1{font-size:25px}h2{font-size:20px}small,.muted{color:#98a9bd}nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button,input,select{font:inherit;padding:10px 14px;border:1px solid #34425c;border-radius:8px;background:#18263a;color:inherit}button{cursor:pointer}button.active{background:#126e79}input{width:100%;margin:12px 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.card{padding:18px;border:1px solid #273951;border-radius:12px;background:#111e31}.big{font-size:27px;font-weight:700;color:#7dddd3}.scroll{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}td,th{text-align:left;padding:11px 12px;border-bottom:1px solid #25344a}th{color:#9caec5}.warn{color:#ffc074}.ok{color:#7dddd3}.detail{background:#111e31;padding:20px;border-radius:10px;margin-top:16px}.badge{font-size:12px;background:#20354c;padding:4px 8px;border-radius:6px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:300px;overflow:auto}a{color:#8cdce0}.note{line-height:1.8;color:#b7c5d7}footer{margin-top:26px;color:#8fa2b9;font-size:13px}
body{font-size:16px}main{max-width:900px;padding:22px 16px}h1{font-size:23px;margin:14px 0}h2{font-size:22px}nav{position:sticky;top:0;z-index:2;background:#0b1220;padding:10px 0;flex-wrap:nowrap;overflow-x:auto}nav button{flex-shrink:0;font-size:14px;padding:10px 12px}.cards{grid-template-columns:repeat(2,1fr);gap:8px}.card{padding:12px}.big{font-size:24px}.selectors{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0}.selectors label{font-size:13px;color:#a5b5c9}.selectors select{display:block;width:100%;margin-top:6px;min-height:48px}.race-head{background:#17263a;border:1px solid #344a65;border-radius:16px;padding:18px;margin:16px 0}.race-head h2{margin:0 0 12px}.race-meta{display:flex;justify-content:space-between;gap:8px;color:#bac9da;font-size:14px}.state{display:inline-block;padding:7px 11px;border-radius:20px;background:#49391e;color:#ffd690;font-size:13px;margin-bottom:12px}.state.ready{background:#16473f;color:#9de9ce}.ticket-box{background:#123b40;border:1px solid #307d83;border-radius:16px;padding:20px;margin:14px 0}.ticket-box h3{margin:0 0 14px;font-size:16px}.formation{font-size:26px;font-weight:750;line-height:1.6;letter-spacing:1px}.ticket-total{margin:14px 0 0;color:#c9eeeb;font-size:16px}.boat-card{background:#142135;border:1px solid #2b405c;border-radius:14px;margin:10px 0;padding:16px}.boat-top{display:flex;align-items:center;gap:12px}.lane{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;font-weight:800;flex-shrink:0}.l1{background:#fff;color:#18202c}.l2{background:#202020;color:#fff;border:1px solid #76808d}.l3{background:#cf4149;color:#fff}.l4{background:#306bc9;color:#fff}.l5{background:#e8c941;color:#242424}.l6{background:#238656;color:#fff}.boat-name{flex:1;font-weight:650}.boat-score{text-align:right;font-size:20px;font-weight:750;color:#86e3d8}.boat-score small{display:block;font-size:11px;font-weight:400;color:#acbdce}.boat-info{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.boat-info div{font-size:16px}.boat-info small{display:block;font-size:11px;margin-bottom:4px}.boat-card details{margin-top:14px;padding-top:12px;border-top:1px solid #2b405c}.boat-card summary,details summary{cursor:pointer;color:#9cdbdf}.boat-card details p{font-size:14px;line-height:1.8}.hint{color:#a9b9ca;font-size:13px;line-height:1.8}.empty{padding:28px 16px;background:#142135;border-radius:14px}.race-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.race-grid .race-head{margin:0}.race-grid h3{margin:0 0 10px;font-size:16px}.mini-status{font-size:13px;line-height:1.9;color:#b9cbdc}footer{line-height:1.8}details{margin:12px 0}button:focus-visible,select:focus-visible{outline:3px solid #80d7d2} @media(max-width:420px){.formation{font-size:23px}.race-meta{font-size:12px}.boat-name{font-size:15px}}
</style>
<main><span class="badge">予想 v0.1 · 固定ルール試作</span><h1>ボートレース データ基盤</h1><p class="muted" id="time"></p><div class="cards" id="metrics"></div><nav id="nav"></nav><div id="content"></div><footer>この画面は書き出し時点のスナップショットです。カルテは蓄積済みデータだけの集計で、将来の的中を保証するスコアではありません。<br>「開催未確認」は非開催の確定情報ではありません。ゼロ件・未取得・配信対象外を区別して確認してください。</footer></main>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('data').textContent),m=data.monitor,p=data.profiles;
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>x==null?'—':(100*x).toFixed(1)+'%';const num=x=>x==null?'—':Number(x).toFixed(3);
const table=(heads,rows)=>'<div class="scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const stats=s=>[s.n,pct(s.win_rate),pct(s.top2_rate),pct(s.top3_rate),num(s.mean_st),num(s.exhibition_to_race_st_delta)];
const statsTable=obj=>table(['条件','走数','1着率','2連率','3連率','平均ST','本番ST−展示ST'],Object.entries(obj).map(([k,s])=>[esc(k),...stats(s)]));
document.getElementById('time').textContent='対象日 '+m.day+' ／ 更新 '+new Date(m.as_of).toLocaleString('ja-JP');
document.getElementById('metrics').innerHTML=[['出走表のある場',m.active_venues+'/24'],['保存レース',m.race_count],['結果保存',m.races.filter(r=>r.result).length],['確認事項',m.issue_count]].map(([a,b])=>'<div class="card"><small>'+a+'</small><div class="big">'+b+'</div></div>').join('');
let tab='予想';const names=['予想','結果・回顧','収集状況','選手カルテ','会場カルテ','モーターカルテ'];
const content=document.getElementById('content');
const raceLabel=r=>{const v=m.venues.find(v=>v.code===r.race_id.slice(8,10));return (v?v.name:'会場不明')+' '+Number(r.race_id.slice(10))+'R';};
function activate(n){tab=n;document.getElementById('nav').innerHTML=names.map(x=>'<button class="'+(x==n?'active':'')+'" data-tab="'+x+'">'+x+'</button>').join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>activate(b.dataset.tab));render();}
function render(){if(tab==='予想'){const venues=[...new Set(data.predictions.map(r=>r.race_id.slice(8,10)))];content.innerHTML='<h2>今日の予想</h2><div class="selectors"><label>会場<select id="race-venue">'+venues.map(code=>'<option value="'+esc(code)+'">'+esc((m.venues.find(v=>v.code===code)||{}).name||code)+'</option>').join('')+'</select></label><label>レース<select id="race"></select></label></div><div id="prediction"></div>';document.getElementById('race-venue').onchange=selectVenue;document.getElementById('race').onchange=showPrediction;selectVenue();return;}if(tab==='結果・回顧'){const days=[...new Set(data.reviews.map(r=>r.day))];content.innerHTML='<h2>結果・回顧</h2><p class="hint">締切前に保存した最新予想と照合。各点100円の参考収支で、実際の購入記録ではありません。</p><label>開催日 <select id="review-day">'+days.map(d=>'<option>'+esc(d)+'</option>').join('')+'</select></label><div id="reviews"></div>';document.getElementById('review-day').onchange=showReviews;showReviews();return;}if(tab==='収集状況'){content.innerHTML='<h2>収集状況</h2><p class="hint">結果は最終収集時点の状態です。</p><div class="race-grid">'+m.races.map(r=>'<article class="race-head"><h3>'+esc(r.venue)+' '+r.number+'R</h3><div class="mini-status">締切 '+esc(r.deadline.slice(11,16))+'<br>出走 '+r.entries+'/6 ・ 展示 '+r.preview+'/6<br><span class="'+(r.result?'ok':'muted')+'">'+(r.result?'結果 保存済み':'結果 更新待ち')+'</span></div>'+(r.issues.length?'<p class="hint warn">'+esc(r.issues.join(' / '))+'</p>':'')+'</article>').join('')+'</div><details><summary>取得元の詳細</summary>'+table(['ソース','HTTP','受信時刻','状態'],m.fetches.map(f=>[esc(f.source),esc(f.status),esc(f.observed_at),esc(f.error||'受信済')]))+'</details>';return;}
if(tab==='選手カルテ'){content.innerHTML='<h2>選手カルテ</h2><input id="q" placeholder="選手名・登録番号で検索"><div id="list"></div><div id="detail"></div>';document.getElementById('q').oninput=()=>players();players();return;}
if(tab==='会場カルテ'){content.innerHTML='<h2>会場カルテ</h2><select id="venue">'+m.venues.map(v=>'<option value="'+v.code+'">'+v.name+'</option>').join('')+'</select> <select id="period"><option>30d</option><option>90d</option><option>365d</option></select><div id="detail"></div>';document.getElementById('venue').onchange=venue;document.getElementById('period').onchange=venue;venue();return;}
content.innerHTML='<h2>モーターカルテ</h2><input id="q" placeholder="場コード・モーター番号で検索"><div id="list"></div><div id="detail"></div>';document.getElementById('q').oninput=motors;motors();}
function players(){const q=document.getElementById('q').value;document.getElementById('list').innerHTML=table(['選手','走数','1着率','2連率','3連率','平均ST'],Object.entries(p.players).filter(([id,x])=>(id+x.name).includes(q)).slice(0,100).map(([id,x])=>['<button data-player="'+id+'">'+esc(x.name)+' ('+id+')</button>',x.all.n,pct(x.all.win_rate),pct(x.all.top2_rate),pct(x.all.top3_rate),num(x.all.mean_st)]));document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{const x=p.players[b.dataset.player];document.getElementById('detail').innerHTML='<div class="detail"><h2>'+esc(x.name)+'</h2><h3>実際の進入コース別</h3>'+statsTable(x.courses)+'<h3>最近の成績</h3>'+statsTable(x.windows)+'<h3>会場別</h3>'+statsTable(x.venues)+'<h3>F本数別</h3>'+statsTable(x.f_count)+'<h3>風速別</h3>'+statsTable(x.wind)+'<details><summary>直近実績・全数値</summary><pre>'+esc(JSON.stringify(x,null,2))+'</pre></details></div>';});}
function venue(){const x=p.venues[document.getElementById('venue').value],v=x.periods[document.getElementById('period').value];document.getElementById('detail').innerHTML='<div class="detail"><h3>コース別</h3>'+statsTable(v.courses)+'<h3>風速 × コース</h3>'+statsTable(v.wind_courses)+'<h3>当日ここまで ('+x.today.race_n+'R)</h3>'+statsTable(x.today.courses)+'<details><summary>条件別の全数値</summary><pre>'+esc(JSON.stringify(v,null,2))+'</pre></details></div>';}
function motors(){const q=document.getElementById('q').value;document.getElementById('list').innerHTML=table(['場:番号:使用期','走数','1着率','2連率','3連率','期確認'],Object.entries(p.motors).filter(([key])=>key.includes(q)).slice(0,100).map(([key,x])=>['<button data-motor="'+esc(key)+'">'+esc(key)+'</button>',x.all.n,pct(x.all.win_rate),pct(x.all.top2_rate),pct(x.all.top3_rate),x.epoch_verified?'確認済':'未確認']));document.querySelectorAll('[data-motor]').forEach(b=>b.onclick=()=>{const x=p.motors[b.dataset.motor];document.getElementById('detail').innerHTML='<div class="detail"><h2>'+esc(b.dataset.motor)+'</h2>'+statsTable({'全走':x.all,'直近20走':x.last_20})+'<h3>実コース別</h3>'+statsTable(x.courses)+'<p class="note">'+esc(x.note)+'</p><pre>'+esc(JSON.stringify(x.recent_runs,null,2))+'</pre></div>';});}
function showReviews(){const day=document.getElementById('review-day').value;const rows=data.reviews.filter(r=>r.day===day);document.getElementById('reviews').innerHTML=rows.length?rows.map(r=>'<article class="boat-card"><h3>'+esc(r.venue)+' '+r.number+'R</h3><span class="state '+(r.hit?'ready':'')+'">'+(r.hit===null?'判定対象外':r.hit?'的中':'不的中')+'</span><div class="formation">結果 '+esc(r.combination||'着順確認中')+'</div><p>3連単払戻 '+(r.payout==null?'未取得':r.payout.toLocaleString()+'円／100円')+'</p>'+(r.tickets.length?'<p>保存買い目 '+esc(r.tickets.join(' ／ '))+'</p><p>'+r.tickets.length+'点 ・ 参考投資 '+r.cost+'円</p><p>参考収支 '+(r.profit==null?'計算保留':(r.profit>0?'+':'')+r.profit.toLocaleString()+'円')+'</p>':'')+'<details open><summary>自動回顧</summary><p class="hint">'+r.comments.map(esc).join('<br>')+'</p></details><details><summary>本番の進入・ST・着順</summary>'+table(['艇','進入','ST','着順','状態'],r.racers.map(x=>[x.lane,esc(x.course),esc(x.st),esc(x.place),esc(x.status)]))+'</details></article>').join(''):'<p class="empty">結果の取得後に表示します。</p>';}
function selectVenue(){const code=document.getElementById('race-venue').value;document.getElementById('race').innerHTML=data.predictions.map((r,i)=>({r,i})).filter(({r})=>r.race_id.slice(8,10)===code).map(({r,i})=>'<option value="'+i+'">'+Number(r.race_id.slice(10))+'R ・ '+esc(r.deadline.slice(11,16))+'</option>').join('');showPrediction();}
function showPrediction(){const pick=document.getElementById('race');const original=pick.value===''?null:data.predictions[Number(pick.value)];const r=original?{...original}:null;const box=document.getElementById('prediction');if(!r){box.innerHTML='<div class="empty">締切前の予想対象がありません。<p class="hint">収集状況タブで結果や更新時刻を確認できます。</p></div>';return;}const closed=Date.now()>=new Date(r.deadline.replace(' ','T')+'+09:00').getTime();if(closed)r.count=0;const age=Math.max(0,Math.floor((Date.now()-new Date(r.at).getTime())/60000));box.innerHTML='<section class="race-head"><h2>'+esc(raceLabel(r))+'</h2><span class="state '+(r.final_ready&&!closed?'ready':'')+'">'+(closed?'締切済み':r.final_ready?'展示反映・参考予想':'展示前・暫定予想')+'</span><div class="race-meta"><span>締切 <strong>'+esc(r.deadline.slice(11,16))+'</strong></span><span>更新 '+esc(new Date(r.at).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}))+'（'+age+'分前）</span></div></section>'+(r.count?'<section class="ticket-box"><h3>3連単 '+(r.final_ready?'参考買い目':'暫定買い目')+'</h3><div class="formation">'+esc(r.formation).replaceAll(' → ','<br>↓<br>')+'</div><p class="ticket-total">'+r.count+'点 × 100円 ＝ <strong>'+r.total_yen.toLocaleString()+'円</strong></p><details><summary>買い目を1点ずつ見る</summary><p>'+r.tickets.map(esc).join(' ／ ')+'</p></details></section>':'<div class="empty">締切済みのため買い目表示を終了しました。</div>')+'<p class="hint">'+(r.final_ready?'固定ルールによる参考予想です。':'展示・直前精査が未完了の暫定候補です。')+(age>15?' 更新から時間が経っています。':'')+'</p><h3>6艇の評価順</h3>'+r.rows.map((x,i)=>'<article class="boat-card"><div class="boat-top"><span class="lane l'+x.lane+'">'+x.lane+'</span><div class="boat-name">'+esc(x.name)+'<small class="muted" style="display:block;font-size:12px;margin-top:4px">評価 '+(i+1)+'位 ・ 想定'+x.course+'コース</small></div><div class="boat-score">'+x.score+'<small>評価点</small></div></div><div class="boat-info"><div><small>展示タイム</small>'+esc(x.exhibition_time)+'</div><div><small>展示ST</small>'+esc(x.exhibition_st)+'</div><div><small>得点率</small>'+esc(x.meeting_points)+'</div></div><details><summary>数値・評価根拠を見る</summary><p>'+x.reasons.map(esc).join('<br>')+'<br>平均ST '+esc(x.average_st)+'</p></details></article>').join('')+'<details><summary>予想の計算方法と未対応項目</summary><p class="hint">'+r.notes.map(esc).join('<br>')+'</p></details>';}
activate(tab);
</script></html>'''

def export_dashboard(store, monitor, profiles):
    output = store.root / 'dashboard'
    output.mkdir(exist_ok=True)
    (output/'monitor.json').write_text(json.dumps(monitor,ensure_ascii=False,indent=2),encoding='utf-8')
    (output/'profiles.json').write_text(json.dumps(profiles,ensure_ascii=False,indent=2),encoding='utf-8')
    # Escape script closing tags from untrusted names/titles.
    predictions = build_predictions(store, monitor['day'], monitor['as_of'])
    reviews = build_reviews(store, monitor['as_of'])
    encoded = dump({'monitor':monitor,'profiles':profiles,'predictions':predictions,'reviews':reviews}).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    path = output / 'index.html'
    temp = output / 'index.tmp'
    temp.write_text(TEMPLATE.replace('__DATA__',encoded),encoding='utf-8')
    temp.replace(path)
    return str(path)
